/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayoutAuth: typeof import('./src/layouts/AppLayoutAuth.vue')['default']
    AppLayoutProfile: typeof import('./src/layouts/AppLayoutProfile.vue')['default']
    Button: typeof import('primevue/button')['default']
    copy: typeof import('./src/modules/faculties/components/form/EditFacultiesForm copy.vue')['default']
    CreateFacultiesForm: typeof import('./src/modules/faculties/components/form/CreateFacultiesForm.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    EditFacultiesForm: typeof import('./src/modules/faculties/components/form/EditFacultiesForm.vue')['default']
    ErrorBoundary: typeof import('./src/error/ErrorBoundary.vue')['default']
    Faculties: typeof import('./src/modules/faculties/components/Faculties.vue')['default']
    FacultiesView: typeof import('./src/modules/faculties/views/FacultiesView.vue')['default']
    FacultiesWidgets: typeof import('./src/modules/faculties/widgets/FacultiesWidgets.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InfoPerson: typeof import('./src/modules/profile/components/PersonInfo.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    PersonInfo: typeof import('./src/modules/profile/components/PersonInfo.vue')['default']
    ProfileWidget: typeof import('./src/modules/profile/widgets/ProfileWidget.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    PublicationsWorks: typeof import('./src/modules/publications/components/PublicationsWorks.vue')['default']
    PublicationWidget: typeof import('./src/modules/publications/widgets/PublicationWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('primevue/sidebar')['default']
    Spinner: typeof import('./src/components/UI/spinner/Spinner.vue')['default']
    UiBurger: typeof import('./src/components/UI/uiBurger.vue')['default']
    UiButton: typeof import('./src/components/UI/uiButton.vue')['default']
    UiInput: typeof import('./src/components/UI/uiInput.vue')['default']
    UiModal: typeof import('./src/components/UI/uiModal.vue')['default']
  }
}
